version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule: 
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 4
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: 'awssdk.*'